project_id = "lascsucrozzhbvlsddxg"

[functions.analyze-beat]
verify_jwt = false

[functions.beat-webhook-handler]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.create-beat-checkout]
verify_jwt = false

[functions.create-beat-product]
verify_jwt = true

[functions.can-create-beatpack]
verify_jwt = true

[functions.can-upload-track]
verify_jwt = true

[functions.signup-with-ip-guard]
verify_jwt = false

[functions.request-payout]
verify_jwt = true

[functions.check-ip-limits]
verify_jwt = false