app = "beat-key-sync"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  VITE_SUPABASE_URL = "https://lascsucrozzhbvlsddxg.supabase.co"
  VITE_SUPABASE_ANON_KEY = "<YOUR_SUPABASE_ANON_KEY>"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
